version = 0.1

[default]
[default.global.parameters]
stack_name = "sam-hello-world-ts"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true